apiVersion: v1
kind: Service
metadata:
  name: ingress-nginx-controller
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: ingress-nginx
    app.kubernetes.io/name: ingress-nginx

  ports:
    - name: http
      port: 80
      targetPort: http
      nodePort: 31863

    - name: https
      port: 443
      targetPort: https
      nodePort: 32372