apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflare-ddns
  namespace: webtest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudflare-ddns
  template:
    metadata:
      labels:
        app: cloudflare-ddns
    spec:
      containers:
        - name: ddns
          image: oznu/cloudflare-ddns:latest
          env:
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: cloudflare-ddns-token
                  key: api-key
            - name: ZONE
              value: tamlabs.co.uk
            - name: SUBDOMAIN
              value: home
            - name: PROXIED
              value: "true"