---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-ddns-token
  namespace: cloudflare-ddns
spec:
  encryptedData:
    cloudflare-ddns-token: AgAunkjm4w0mHGwNy+5yoFBRp0ED1Q13s6uJFfKZShjKRvarLMJNoQhlK0ouciGqAIBEIh1TYBGxJyf5dHAcY3CDZDHavvzJa9MRxwI+BBtvlsFjgpTemEg2gdVSIvNbwpXwnPkmwTYY4UQXJeXxeKtmyYaNcE+UcqN8LFIpNtlwAvzsibA6XvwemD/NzzvH3eNzfuHYqTqmPU7nJ71DljqNV+DHI3Abm9kh6Rae7J047nTN1MbVlXy0hdMbBN2tDtHuhUYx/lez2ifEsHW0t0wPTM+ECbWsfNcVZU4Ciq9HdW4icGCL/7PxdtZqjH9NRd8N40y/oXoqlXqpZK+9TDM4avyn+QaU7SSzX1iD1BuHN/RTY7JDcIi3ZhwlNe48xM6wBRg9JcSa4HrLz8sbR9xcgO2gsZjrd+XhmDR6tutEWf/coIHbeiwqgdZr0ymx71T6Uk7+m0aAba2C/5KYo41a6HoHHOlkRo1eleQeRfQn3Jz63ljPWlyHPJPZy8ztOSZbB8laobV1ETnFfan1ohKWiC27r0KuTqrlJ+h4/0HMoQbsAwkDyaDeJnBUOCc0JFTRDXW1P3eC5+Hs6jxJrUyijSA+5BFhILgANGjWfzQ8dexOjQbST1J2Cc1VXe4Jpkz/k0PnDDphY9TDhrMaa7jdN224wKd/mYTSS047vAPTyJLYWneKDkwecF9WkcgMOrQKpBQhHLrd9q8SUdKlXYDGBFckov2TEBdQ+vszYOJq6w988Bttz5w7OzoIx82bO2/+XmfDxw==
  template:
    metadata:
      name: cloudflare-ddns-token
      namespace: cloudflare-ddns
