---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-ddns-token
  namespace: cloudflare-ddns
spec:
  encryptedData:
    cloudflare-ddns-token: AgCsQ8UJ3f3W3dyqzEACtRg8TZYF+aBCFOe+cpHhv0mLF3D3GOYGd8pvCtWm6r4b0Xw2UUwQQN5KhMqtm8yphrzJwU82VblV/lEk3gdt77shgUiedw+XNltAhZX4ziV/zy9258Vk+3dQS/kFsHgM5bcWYFusgB9ZUSmWfseqWOzO5NmUjUD0YMOnEFIWbe1KuYCouEdeZrKN8LktwLepqAZdXmzpPStTpzdvZdsqP3/PC4RNc15K6Kgk25kfW3CtaGejcsRPusnj0FSzyJT/xuYGKHfp/CfjcVvxWzms4TqHqda0z/ADGdsyt6/f0HTfnNXoXSeGCWoClXURav/1f3i/8FyqiGWfji/X+U6/0DxS5YeBhthAJmAIrxKGtaTCPJM9O7UuE/yMccapcqdX39YWQzNNXyf3QTuEadz910l/hZ4hVoh5XVHlJ6QTM8zBQwlEVHg4h6zTIeGuA0eeFNOatt5lFE2qYDlyDVHgciUTmjvn/UDGOju4MKr1F4syRDhg2YN/Bl0KgihUfI9b9DxDpzlj+typw4yGppLClq6sUAIE9Jz1a7MCBI0zOFDWDR2lB5EiKUCyMhSpBOtdGEaK4A8uPKqMg//zdYXrpfPNssI53uBGI7yDu67GiQT7zSbvA9EXZj2psYsQMok71I92RxdobVsXuX+CvnQQkSCea+pHq3t/PTzabQ2WIqr03l/NYKCEzE/w3ezGD+m8WI8aVN+IDhxs9RFQ4tLe27q3Ja6+vKD6ELGkp7yJKoLnVYsJ8tLyiA==
  template:
    metadata:
      name: cloudflare-ddns-token
      namespace: cloudflare-ddns
