apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: web
resources:
  - namespace.yaml
  - configmap.yaml
  - sealed-secret.yaml
  - deployment.yaml
  - service.yaml
  - cluster-issuer.yaml
  - certificate.yaml
  - ingress.yaml
