apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: nginx-hello-secret
  namespace: web
spec:
  encryptedData:
    hello: AgReplaceMeWithKubesealOutput
  template:
    metadata:
      name: nginx-hello-secret
      namespace: web
    type: Opaque
