apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflared
  namespace: cloudflared
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudflared
  template:
    metadata:
      labels:
        app: cloudflared
    spec:
      containers:
        - name: cloudflared
          image: cloudflare/cloudflared:2026.3.0
          args:
            - tunnel
            - --no-autoupdate
            - run
            - --token
            - eyJhIjoiMzNmNzQ0MjIxNTIyOTc5MDkyNjRlZDIyZWY5MzY4YTUiLCJ0IjoiYjI2M2NkOGEtZmE3ZC00YTFlLTlmYTktNWU5MGNmM2ZiNGJlIiwicyI6Ik5XRmhOR014TldJdE5XSTJaUzAwTlRjM0xXSTFOekl0WVdSalptVXdNVEF4Tm1VMCJ9

