apiVersion: v1
kind: PersistentVolume
metadata:
  name: amp-data-pv
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: alphastore.tailf8053b.ts.net
    path: /mnt/user/appdata/amp_new
