apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-controller
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/thomas-massey/homelab-k8-config
    targetRevision: main
    path: core/ingress-controller
  destination:
    server: https://kubernetes.default.svc
    namespace: ingress-nginx
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
